=== BackEndTea/Learning/XML/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="merge_request">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="merge_request_number">
                    <xs:annotation>
                        <xs:documentation>The Merge request number, not including any leading # or !</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="title" type="xs:string" />
                <xs:element name="code" type="xs:string">
                    <xs:annotation>
                        <xs:documentation>The commit diff, represented as a string</xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element name="commits">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="commit" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="hash" type="xs:string"/>
                                        <xs:element name="title">
                                            <xs:annotation>
                                                <xs:documentation>The title of the commit, which may be no longer than 72 characters</xs:documentation>
                                            </xs:annotation>
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="72"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="body" type="xs:string" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="message" type="xs:string" />
                <xs:element name="comments" type="xs:string" minOccurs="0"/>
                <xs:element name="status" type="xs:boolean" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BackEndTea/Learning/XML/mergerequest.xml
<?xml version="1.0" encoding="UTF-8"?>

<merge_request xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
    <merge_request_number>12</merge_request_number>
    <title>Fix bugs</title>
    <code>
        Code diff goes here...
    </code>
    <commits>
        <commit>
            <hash>asdf83asdf0asdf12ja</hash>
            <title>Fix</title>
        </commit>
        <commit>
            <hash>asdf83aadsdf0asdfja</hash>
            <title>Real fix</title>
        </commit>
        <commit>
            <hash>asdf83asdf0asdf0pja</hash>
            <title>Actual real fix now</title>
        </commit>
    </commits>
    <message>
        This merge request fixes a big bug
    </message>
    <status>false</status>
</merge_request>
